# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install python-software-properties

  # LLVM 3.4 / 3.5 / snapshots
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

  - sudo add-apt-repository --yes ppa:boost-latest/ppa

  # g++4.8.1
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

  - sudo add-apt-repository --yes ppa:h-rayflood/llvm

install:
  - sudo apt-get update
  - sudo apt-get install -y $LLVM_PACKAGE libconfig++8-dev python-sphinx libboost-program-options1.55-dev libboost-regex1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev
  -
    if [[ "${CXX}" == "g++" ]]; then
      sudo apt-get install g++-4.8; export CXX="g++-4.8";
    fi
  -
    if [[ "${CXX}" == "clang++" ]]; then
      sudo apt-get install --allow-unauthenticated -qq clang-3.4; export CXX="clang++-3.4";
    fi

  - wget http://ftp.heanet.ie/mirrors/gnu/bison/bison-3.0.2.tar.gz
  - tar -xvzf bison-3.0.2.tar.gz
  - cd bison-3.0.2
  - ./configure && make && sudo make install
  - cd ..

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make

env:
  - BUILD_TYPE=Debug LLVM_PACKAGE="llvm-3.4 llvm-3.4-dev"
  - BUILD_TYPE=Release LLVM_PACKAGE="llvm-3.4 llvm-3.4-dev"
  - BUILD_TYPE=Debug LLVM_PACKAGE="llvm-3.5 llvm-3.5-dev"
  - BUILD_TYPE=Release LLVM_PACKAGE="llvm-3.5 llvm-3.5-dev"
  - BUILD_TYPE=Debug LLVM_PACKAGE="llvm-3.6 llvm-3.6-dev"
  - BUILD_TYPE=Release LLVM_PACKAGE="llvm-3.6 llvm-3.6-dev"