# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm-3.5-dev clang-3.5

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make

env:
  matrix:
    - BUILD_TYPE=debug
    - BUILD_TYPE=release