# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

language: cpp

compiler:
  - gcc
  - clang

before_install:
  # LLVM 3.4 / 3.5 / snapshots
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

install:
  - sudo apt-get update
  - sudo apt-get install -y $LLVM_PACKAGE libconfig++8-dev python-sphinx libboost-dev libboost-program-options-dev
  -
    if [[ "${CXX}" == "g++" ]]; then
      sudo apt-get install g++-4.8; export CXX="g++-4.8";
    fi
  -
    if [[ "${CXX}" == "clang++" ]]; then
      sudo apt-get install --allow-unauthenticated -qq clang-3.4; export CXX="clang++-3.4";
    fi

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make

env:
  - BUILD_TYPE=Debug LLVM_PACKAGE="llvm-3.4 llvm-3.4-dev"
  - BUILD_TYPE=Release LLVM_PACKAGE="llvm-3.4 llvm-3.4-dev"
  - BUILD_TYPE=Debug LLVM_PACKAGE="llvm-3.5 llvm-3.5-dev"
  - BUILD_TYPE=Release LLVM_PACKAGE="llvm-3.5 llvm-3.5-dev"
  - BUILD_TYPE=Debug LLVM_PACKAGE="llvm-3.6 llvm-3.6-dev"
  - BUILD_TYPE=Release LLVM_PACKAGE="llvm-3.6 llvm-3.6-dev"